//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoMute.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarPool
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CarPool()
        {
            this.CarPoolUsers = new HashSet<CarPoolUser>();
        }
    
        public int Id { get; set; }
        public System.DateTime DepartureTime { get; set; }
        public System.DateTime ExpectedArrivalTime { get; set; }
        public string Origin { get; set; }
        public int DaysAvailable { get; set; }
        public string Destination { get; set; }
        public int AvilableSeats { get; set; }
        public int OwnerId { get; set; }
        public string Notes { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarPoolUser> CarPoolUsers { get; set; }
    }
}
