//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoMute.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarPoolUser
    {
        public int Id { get; set; }
        public int CarPoolId { get; set; }
        public int UserId { get; set; }
    
        public virtual CarPool CarPool { get; set; }
        public virtual User User { get; set; }
    }
}
