//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoMute.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarPools
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CarPools()
        {
            this.JoinedCarPools = new HashSet<JoinedCarPools>();
        }
    
        public System.DateTime DepartureTime { get; set; }
        public System.DateTime ExpectA_Time { get; set; }
        public string Origin { get; set; }
        public string Destination { get; set; }
        public int Avail_Seats { get; set; }
        public string Owner_Leader { get; set; }
        public string Email { get; set; }
        public System.DateTime PoolCreationDate { get; set; }
        public Nullable<int> DaysAvailable { get; set; }
        public string Notes { get; set; }
    
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JoinedCarPools> JoinedCarPools { get; set; }
    }
}
