//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoMute.Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class carreg
    {
        [Key]
        public string Departure_Time { get; set; }
        public string Expected_Arrival_Time { get; set; }
        public string Origin { get; set; }
        public string Destination { get; set; }
        public string Available_Seats { get; set; }
        public string Owner_Leader { get; set; }
        public string Notes { get; set; }
    }
}
