//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoMute.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Joined_Car_Pool
    {
        public int Joined_Car_Pool_ID { get; set; }
        public Nullable<int> User_ID { get; set; }
        public Nullable<int> Car_Pool_ID { get; set; }
        public Nullable<System.DateTime> Date_Joined { get; set; }
        public Nullable<System.TimeSpan> Departure_Time { get; set; }
        public Nullable<System.TimeSpan> Expected_Arrival_Time { get; set; }
    
        public virtual Car_Pool Car_Pool { get; set; }
        public virtual User User { get; set; }
    }
}
