//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoMute.Web.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CoMuteEntities1 : DbContext
    {
        public CoMuteEntities1()
            : base("name=CoMuteEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CarPools> CarPools { get; set; }
        public virtual DbSet<JoinedCarPools> JoinedCarPools { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
