// <auto-generated />
namespace CoMute.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Initial2002234CarpoolCarpoolDays : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Initial2002234CarpoolCarpoolDays));
        
        string IMigrationMetadata.Id
        {
            get { return "202302232221254_Initial.200223.4-Carpool-CarpoolDays"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
