//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoMute.Web.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarpoolsJoined
    {
        public int CarpoolJoinedID { get; set; }
        public int UserJoinID { get; set; }
        public int TheCarPoolID { get; set; }
    
        public virtual CarpoolsTable CarpoolsTable { get; set; }
        public virtual UsersList UsersList { get; set; }
    }
}
