//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoMute.Web.Models.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ComuteDBEntities : DbContext
    {
        public ComuteDBEntities()
            : base("name=ComuteDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CarpoolsJoined> CarpoolsJoineds { get; set; }
        public virtual DbSet<CarpoolsTable> CarpoolsTables { get; set; }
        public virtual DbSet<UsersList> UsersLists { get; set; }
    }
}
