# Generated by Django 4.0.5 on 2022-06-29 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_passengers_passenger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpool',
            name='DaysAvailable',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='carpool',
            name='SeatsAvailable',
            field=models.PositiveBigIntegerField(),
        ),
    ]
