# Generated by Django 4.0.5 on 2022-06-29 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_carpool_daysavailable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpool',
            name='DepartureTime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='carpool',
            name='ExpectedArrivalTime',
            field=models.DateTimeField(),
        ),
    ]
