# Generated by Django 4.0.5 on 2022-06-29 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_carpool_departuretime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpool',
            name='Notes',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
