//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoMute.Web.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CarPoolEntities : DbContext
    {
        public CarPoolEntities()
            : base("name=CarPoolEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Passenger_Pool> Passenger_Pool { get; set; }
        public virtual DbSet<Register> Registers { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<User_Car_Pool> User_Car_Pool { get; set; }
    }
}
