//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoMute.Web.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbCoMuteEntities : DbContext
    {
        public dbCoMuteEntities()
            : base("name=dbCoMuteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblRegister> tblRegisters { get; set; }
        public virtual DbSet<tblUserCarPool> tblUserCarPools { get; set; }

        public System.Data.Entity.DbSet<CoMute.Web.Models.Dto.Carpool> Carpools { get; set; }
    }
}
