//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoMute.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Passenger_Pool
    {
        public int Passenger_Pool_ID { get; set; }
        public Nullable<int> Register_ID { get; set; }
        public Nullable<int> User_Car_Pool_ID { get; set; }
        public Nullable<int> Status_ID { get; set; }
        public Nullable<System.DateTime> Date_Joined { get; set; }
    
        public virtual Register Register { get; set; }
        public virtual Status Status { get; set; }
        public virtual User_Car_Pool User_Car_Pool { get; set; }
    }
}
