//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoMute.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserCarPool
    {
        public int CarPoolID { get; set; }
        public System.TimeSpan Depart_Time { get; set; }
        public string Origin { get; set; }
        public Nullable<int> Days_Avail { get; set; }
        public string Destination { get; set; }
        public int Avail_Seats { get; set; }
        public string Owner_Leader { get; set; }
        public string Notes { get; set; }
        public int UserID { get; set; }
        public System.TimeSpan Arrival_Time { get; set; }
        public System.DateTime Date_Created { get; set; }
        public System.DateTime Date_Joined { get; set; }
        public int PassengerPoolID { get; set; }
    
        public virtual tblRegister tblRegister { get; set; }
    }
}
