//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoMute.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Car_Pool
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User_Car_Pool()
        {
            this.Passenger_Pool = new HashSet<Passenger_Pool>();
        }
    
        public int User_Car_Pool_ID { get; set; }
        public System.TimeSpan Departure { get; set; }
        public System.TimeSpan Expected_Arrival { get; set; }
        public string Origin { get; set; }
        public string Days { get; set; }
        public string Destination { get; set; }
        public int Available_Seats { get; set; }
        public Nullable<int> Number_Of_Passengers { get; set; }
        public string Notes { get; set; }
        public Nullable<int> Register_ID { get; set; }
        public Nullable<System.DateTime> Date_Created { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Passenger_Pool> Passenger_Pool { get; set; }
        public virtual Register Register { get; set; }
    }
}
