USE [master]
GO

/****** Object:  Database [Co-mute]    Script Date: 9/6/2022 1:47:09 PM ******/
CREATE DATABASE [Co-mute]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Co-mute', FILENAME = N'E:\MSSQL\MSSQL15.MSSQLSERVER\MSSQL\DATA\Co-mute.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Co-mute_log', FILENAME = N'E:\MSSQL\MSSQL15.MSSQLSERVER\MSSQL\DATA\Co-mute_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Co-mute].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Co-mute] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Co-mute] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Co-mute] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Co-mute] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Co-mute] SET ARITHABORT OFF 
GO

ALTER DATABASE [Co-mute] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Co-mute] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Co-mute] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Co-mute] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Co-mute] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Co-mute] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Co-mute] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Co-mute] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Co-mute] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Co-mute] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Co-mute] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Co-mute] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Co-mute] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Co-mute] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Co-mute] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Co-mute] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Co-mute] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Co-mute] SET RECOVERY FULL 
GO

ALTER DATABASE [Co-mute] SET  MULTI_USER 
GO

ALTER DATABASE [Co-mute] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Co-mute] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Co-mute] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Co-mute] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Co-mute] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Co-mute] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Co-mute] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Co-mute] SET  READ_WRITE 
GO

