// <auto-generated />
using System;
using FSWebApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FSWebApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230408083032_initAgain")]
    partial class initAgain
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("FSWebApi.Models.Carpool", b =>
                {
                    b.Property<Guid>("CarpoolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<TimeSpan>("ArrivalTime")
                        .HasColumnType("time(6)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DayAvailable")
                        .HasColumnType("datetime(6)");

                    b.Property<TimeSpan>("DepartureTime")
                        .HasColumnType("time(6)");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("OwnerID")
                        .HasColumnType("char(36)");

                    b.Property<int>("Seats")
                        .HasColumnType("int");

                    b.HasKey("CarpoolId");

                    b.HasIndex("OwnerID");

                    b.ToTable("carpools");
                });

            modelBuilder.Entity("FSWebApi.Models.CarpoolMember", b =>
                {
                    b.Property<Guid>("CarpoolId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("CarpoolId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("carpoolMembers");
                });

            modelBuilder.Entity("FSWebApi.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UserId");

                    b.ToTable("users");
                });

            modelBuilder.Entity("FSWebApi.Models.Carpool", b =>
                {
                    b.HasOne("FSWebApi.Models.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FSWebApi.Models.CarpoolMember", b =>
                {
                    b.HasOne("FSWebApi.Models.Carpool", null)
                        .WithMany("Members")
                        .HasForeignKey("CarpoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FSWebApi.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FSWebApi.Models.Carpool", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
