#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoMute.DL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
    using CoMute.BE;

    [global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CoMuteVersion")]
	public partial class EntitiesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertUser(User instance);
    partial void UpdateUser(User instance);
    partial void DeleteUser(User instance);
    partial void InsertCarPool(CarPool instance);
    partial void UpdateCarPool(CarPool instance);
    partial void DeleteCarPool(CarPool instance);
    partial void InsertJoinLeaveCarPool(JoinLeaveCarPool instance);
    partial void UpdateJoinLeaveCarPool(JoinLeaveCarPool instance);
    partial void DeleteJoinLeaveCarPool(JoinLeaveCarPool instance);
    #endregion
		
		public EntitiesDataContext() : 
				base(global::CoMute.DL.Properties.Settings.Default.CoMuteVersionConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public EntitiesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EntitiesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EntitiesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EntitiesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<User> Users
		{
			get
			{
				return this.GetTable<User>();
			}
		}
		
		public System.Data.Linq.Table<CarPool> CarPools
		{
			get
			{
				return this.GetTable<CarPool>();
			}
		}
		
		public System.Data.Linq.Table<JoinLeaveCarPool> JoinLeaveCarPools
		{
			get
			{
				return this.GetTable<JoinLeaveCarPool>();
			}
		}
	}
	
}
#pragma warning restore 1591
