//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvCCarPool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarPoolList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CarPoolList()
        {
            this.CarPoolUserLists = new HashSet<CarPoolUserList>();
        }
    
        public string Destination { get; set; }
        public System.DateTime ArrivalTime { get; set; }
        public System.DateTime DepartureTime { get; set; }
        public string Origin { get; set; }
        public int AvailableSeats { get; set; }
        public string Owner { get; set; }
        public string Notes { get; set; }
        public int CarPoolId { get; set; }
        public int Id { get; set; }
    
        public virtual CarPoolUser CarPoolUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarPoolUserList> CarPoolUserLists { get; set; }
    }
}
