//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvCCarPool.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CarPoolEntities1 : DbContext
    {
        public CarPoolEntities1()
            : base("name=CarPoolEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CarPoolList> CarPoolLists { get; set; }
        public virtual DbSet<CarPoolUser> CarPoolUsers { get; set; }
        public virtual DbSet<CarPoolUserList> CarPoolUserLists { get; set; }
    }
}
