//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvCCarPool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarPoolUserList
    {
        public int Idx { get; set; }
        public int UserId { get; set; }
        public int CarPoolId { get; set; }
    
        public virtual CarPoolList CarPoolList { get; set; }
        public virtual CarPoolUser CarPoolUser { get; set; }
    }
}
